[build]
builder = "nixpacks"

[[services]]
name = "ghi"
template = "node"
command = "cd ghi && serve -s build -l $PORT"

[[services]]
name = "api"
template = "python"
command = "cd api && uvicorn main:app --host 0.0.0.0 --port $PORT"

[deploy]
startCommand = "nixpacks start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
